spring.application.name=ms-pedido
spring.datasource.url=jdbc:mysql://localhost:3306/db_pedido?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Base URLs para WebClient (ajusta según puertos reales)
ms.usuarios.base-url=http://localhost:8081
ms.catalogo.base-url=http://localhost:8082
ms.stock.base-url=http://localhost:8083
ms.pago.base-url=http://localhost:8084

# Puesto opcional
server.port=8085